sonar.projectKey=NataliiaBurmei_advent-of-test
sonar.organization=nataliiaburmei
sonar.host.url=https://sonarcloud.io

sonar.projectName=advent-of-test
sonar.projectVersion=1.0

sonar.sources=src
sonar.exclusions=**/*.test.ts,**/*.fuzz.test.ts,**/node_modules/**,**/dist/**

sonar.tests=src
sonar.test.inclusions=**/*.test.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
